// Auto-generated by YDWS-CodingBank tools/export_course_js.py
// Do not edit manually unless you know what you are doing.

const course = {
  "code": "JSS01",
  "title": "字串處理",
  "type": "programming",
  "mode": "learning",
  "description": "以字串長度、字元索引、逐字元遍歷與字串判斷為核心的文字處理課程。",
  "source": {
    "project": "YDWS-CodingBank",
    "generatedAt": "2026-07-05T16:34:27+08:00",
    "sourceCsv": "data\\problem_bank_master_tagged.csv",
    "version": "PB05-3A"
  },
  "tasks": [
    {
      "id": "JSS01-D01",
      "title": "字串長度",
      "problemTitle": "字串長度",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "demo",
      "difficulty": "L1",
      "blocklyFit": "高",
      "description": "題目：字串長度\n\n題目說明\n\n輸入一個字串，請輸出這個字串的長度。本題用來示範把文字視為資料並取得長度。",
      "inputDescription": "第一行：一個不含空白的字串 S。",
      "outputDescription": "輸出 S 的長度。",
      "statement": {
        "description": "題目：字串長度\n\n題目說明\n\n輸入一個字串，請輸出這個字串的長度。本題用來示範把文字視為資料並取得長度。",
        "input": "第一行：一個不含空白的字串 S。",
        "output": "輸出 S 的長度。"
      },
      "examples": [
        {
          "input": "apple",
          "output": "5",
          "explanation": "apple 有 5 個字元。"
        },
        {
          "input": "A",
          "output": "1",
          "explanation": "A 有 1 個字元。"
        }
      ],
      "testCases": [
        {
          "input": "apple",
          "expectedOutput": "5",
          "output": "5",
          "score": 20,
          "hidden": false
        },
        {
          "input": "A",
          "expectedOutput": "1",
          "output": "1",
          "score": 20,
          "hidden": false
        },
        {
          "input": "Blockly",
          "expectedOutput": "7",
          "output": "7",
          "score": 20,
          "hidden": false
        },
        {
          "input": "code123",
          "expectedOutput": "7",
          "output": "7",
          "score": 20,
          "hidden": false
        },
        {
          "input": "Taiwan",
          "expectedOutput": "6",
          "output": "6",
          "score": 20,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "JSS01-D02",
      "title": "第一個與最後一個字元",
      "problemTitle": "第一個與最後一個字元",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "demo",
      "difficulty": "L1",
      "blocklyFit": "高",
      "description": "題目：第一個與最後一個字元\n\n題目說明\n\n輸入一個字串，請輸出第一個字元與最後一個字元，兩個結果各佔一行。本題用來示範字串索引與位置概念。",
      "inputDescription": "第一行：一個不含空白的字串 S。",
      "outputDescription": "第一行：S 的第一個字元。\n\n第二行：S 的最後一個字元。",
      "statement": {
        "description": "題目：第一個與最後一個字元\n\n題目說明\n\n輸入一個字串，請輸出第一個字元與最後一個字元，兩個結果各佔一行。本題用來示範字串索引與位置概念。",
        "input": "第一行：一個不含空白的字串 S。",
        "output": "第一行：S 的第一個字元。\n\n第二行：S 的最後一個字元。"
      },
      "examples": [
        {
          "input": "apple",
          "output": "a\ne",
          "explanation": "apple 的第一個字元是 a，最後一個字元是 e。"
        },
        {
          "input": "Z",
          "output": "Z\nZ",
          "explanation": "只有一個字元時，第一個與最後一個相同。"
        }
      ],
      "testCases": [
        {
          "input": "apple",
          "expectedOutput": "a\ne",
          "output": "a\ne",
          "score": 20,
          "hidden": false
        },
        {
          "input": "Z",
          "expectedOutput": "Z\nZ",
          "output": "Z\nZ",
          "score": 20,
          "hidden": false
        },
        {
          "input": "Blockly",
          "expectedOutput": "B\ny",
          "output": "B\ny",
          "score": 20,
          "hidden": false
        },
        {
          "input": "code123",
          "expectedOutput": "c\n3",
          "output": "c\n3",
          "score": 20,
          "hidden": false
        },
        {
          "input": "Taiwan",
          "expectedOutput": "T\nn",
          "output": "T\nn",
          "score": 20,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "JSS01-D03",
      "title": "逐字元輸出",
      "problemTitle": "逐字元輸出",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "demo",
      "difficulty": "L1",
      "blocklyFit": "高",
      "description": "題目：逐字元輸出\n\n題目說明\n\n輸入一個字串，請依序輸出每一個字元，每個字元各佔一行。本題用來示範用迴圈逐一處理字元。",
      "inputDescription": "第一行：一個不含空白的字串 S。",
      "outputDescription": "依序輸出 S 的每一個字元，每個字元各佔一行。",
      "statement": {
        "description": "題目：逐字元輸出\n\n題目說明\n\n輸入一個字串，請依序輸出每一個字元，每個字元各佔一行。本題用來示範用迴圈逐一處理字元。",
        "input": "第一行：一個不含空白的字串 S。",
        "output": "依序輸出 S 的每一個字元，每個字元各佔一行。"
      },
      "examples": [
        {
          "input": "cat",
          "output": "c\na\nt",
          "explanation": "依序輸出 c、a、t。"
        },
        {
          "input": "Hi",
          "output": "H\ni",
          "explanation": "依序輸出 H、i。"
        }
      ],
      "testCases": [
        {
          "input": "cat",
          "expectedOutput": "c\na\nt",
          "output": "c\na\nt",
          "score": 20,
          "hidden": false
        },
        {
          "input": "Hi",
          "expectedOutput": "H\ni",
          "output": "H\ni",
          "score": 20,
          "hidden": false
        },
        {
          "input": "A",
          "expectedOutput": "A",
          "output": "A",
          "score": 20,
          "hidden": false
        },
        {
          "input": "code",
          "expectedOutput": "c\no\nd\ne",
          "output": "c\no\nd\ne",
          "score": 20,
          "hidden": false
        },
        {
          "input": "123",
          "expectedOutput": "1\n2\n3",
          "output": "1\n2\n3",
          "score": 20,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "JSS01-P01",
      "title": "指定字元出現次數",
      "problemTitle": "指定字元出現次數",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "practice",
      "difficulty": "L2",
      "blocklyFit": "高",
      "description": "題目：指定字元出現次數\n\n題目說明\n\n第一行輸入一個字串 S，第二行輸入一個字元 C。請計算 C 在 S 中出現幾次。本題用來練習字串遍歷與條件計數。",
      "inputDescription": "第一行：一個不含空白的字串 S。\n\n第二行：一個字元 C。",
      "outputDescription": "輸出 C 在 S 中出現的次數。",
      "statement": {
        "description": "題目：指定字元出現次數\n\n題目說明\n\n第一行輸入一個字串 S，第二行輸入一個字元 C。請計算 C 在 S 中出現幾次。本題用來練習字串遍歷與條件計數。",
        "input": "第一行：一個不含空白的字串 S。\n\n第二行：一個字元 C。",
        "output": "輸出 C 在 S 中出現的次數。"
      },
      "examples": [
        {
          "input": "banana\na",
          "output": "3",
          "explanation": "a 在 banana 中出現 3 次。"
        },
        {
          "input": "code\nz",
          "output": "0",
          "explanation": "z 沒有出現。"
        }
      ],
      "testCases": [
        {
          "input": "banana\na",
          "expectedOutput": "3",
          "output": "3",
          "score": 20,
          "hidden": false
        },
        {
          "input": "code\nz",
          "expectedOutput": "0",
          "output": "0",
          "score": 20,
          "hidden": false
        },
        {
          "input": "hello\nl",
          "expectedOutput": "2",
          "output": "2",
          "score": 20,
          "hidden": false
        },
        {
          "input": "aaaaa\na",
          "expectedOutput": "5",
          "output": "5",
          "score": 20,
          "hidden": false
        },
        {
          "input": "Blockly\no",
          "expectedOutput": "1",
          "output": "1",
          "score": 20,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "JSS01-P02",
      "title": "簡易格式檢查",
      "problemTitle": "簡易格式檢查",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "practice",
      "difficulty": "L2",
      "blocklyFit": "高",
      "description": "題目：簡易格式檢查\n\n題目說明\n\n輸入一個字串 S。若 S 的長度為 4，輸出 OK；否則輸出 NG。本題用來練習簡單的字串格式檢查。",
      "inputDescription": "第一行：一個不含空白的字串 S。",
      "outputDescription": "若 S 長度為 4，輸出 OK；否則輸出 NG。",
      "statement": {
        "description": "題目：簡易格式檢查\n\n題目說明\n\n輸入一個字串 S。若 S 的長度為 4，輸出 OK；否則輸出 NG。本題用來練習簡單的字串格式檢查。",
        "input": "第一行：一個不含空白的字串 S。",
        "output": "若 S 長度為 4，輸出 OK；否則輸出 NG。"
      },
      "examples": [
        {
          "input": "ABCD",
          "output": "OK",
          "explanation": "ABCD 長度為 4。"
        },
        {
          "input": "ABC",
          "output": "NG",
          "explanation": "ABC 長度不是 4。"
        }
      ],
      "testCases": [
        {
          "input": "ABCD",
          "expectedOutput": "OK",
          "output": "OK",
          "score": 20,
          "hidden": false
        },
        {
          "input": "ABC",
          "expectedOutput": "NG",
          "output": "NG",
          "score": 20,
          "hidden": false
        },
        {
          "input": "1234",
          "expectedOutput": "OK",
          "output": "OK",
          "score": 20,
          "hidden": false
        },
        {
          "input": "hello",
          "expectedOutput": "NG",
          "output": "NG",
          "score": 20,
          "hidden": false
        },
        {
          "input": "A",
          "expectedOutput": "NG",
          "output": "NG",
          "score": 20,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-10-0",
      "title": "多科成績計算",
      "problemTitle": "多科成績計算",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：多科成績計算\n\n題目說明\n\n小明參加了數學、英文、自然...等多科的段考，老師希望能快速算出總分與平均分數，並判斷是否及格。\n\n請設計程式，輸入多科的成績，計算總分與平均。\n\n第一行輸入共有幾科\n\n第二行依序輸入各科成績，科成績之間以空白間隔\n\n計算總分，平均成績以四捨五入取整數\n\n如果平均分數大於等於 60，就輸出「及格」，否則輸出「不及格」。\n\n這題可以訓練你如何處理多筆資料的加總、平均計算，並搭配條件判斷。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n3\n80 70 90\n\n240\n80\n及格\n\n第一行輸入3，表示後面會有3個數字輸入\n\n第二行輸入80 70 90，經過計算後\n\n總分180、平均80、及格\n\n6\n50 41 60 55 70 65\n\n341\n57\n不及格\n\n第一行輸入6，表示後面會有3個數字輸入\n\n第二行輸入50 41 60 55 70 65，經過計算後\n\n程式輸出總分341、平均57、不及格",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "題目：多科成績計算\n\n題目說明\n\n小明參加了數學、英文、自然...等多科的段考，老師希望能快速算出總分與平均分數，並判斷是否及格。\n\n請設計程式，輸入多科的成績，計算總分與平均。\n\n第一行輸入共有幾科\n\n第二行依序輸入各科成績，科成績之間以空白間隔\n\n計算總分，平均成績以四捨五入取整數\n\n如果平均分數大於等於 60，就輸出「及格」，否則輸出「不及格」。\n\n這題可以訓練你如何處理多筆資料的加總、平均計算，並搭配條件判斷。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n3\n80 70 90\n\n240\n80\n及格\n\n第一行輸入3，表示後面會有3個數字輸入\n\n第二行輸入80 70 90，經過計算後\n\n總分180、平均80、及格\n\n6\n50 41 60 55 70 65\n\n341\n57\n不及格\n\n第一行輸入6，表示後面會有3個數字輸入\n\n第二行輸入50 41 60 55 70 65，經過計算後\n\n程式輸出總分341、平均57、不及格",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "3\n80 70 90",
          "output": "240\n80\n及格",
          "explanation": "第一行輸入3，表示後面會有3個數字輸入\n第二行輸入80 70 90，經過計算後\n總分180、平均80、及格"
        },
        {
          "input": "6\n50 41 60 55 70 65",
          "output": "341\n57\n不及格",
          "explanation": "第一行輸入6，表示後面會有3個數字輸入\n第二行輸入50 41 60 55 70 65，經過計算後\n程式輸出總分341、平均57、不及格"
        }
      ],
      "testCases": [
        {
          "input": "3\n20 60 90",
          "expectedOutput": "170 57 不及格",
          "output": "170 57 不及格",
          "score": 10,
          "hidden": false
        },
        {
          "input": "6\n50 41 60 55 70 65",
          "expectedOutput": "341 57 不及格",
          "output": "341 57 不及格",
          "score": 10,
          "hidden": false
        },
        {
          "input": "5\n80 70 75 85 90",
          "expectedOutput": "400 80 及格",
          "output": "400 80 及格",
          "score": 10,
          "hidden": false
        },
        {
          "input": "1\n55",
          "expectedOutput": "55 55 不及格",
          "output": "55 55 不及格",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-10-1",
      "title": "加權成績計算",
      "problemTitle": "加權成績計算",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：加權成績計算\n\n題目說明\n\n大明綜合高中辦理考試，不同科系考試科目數量、每周上課時數不一定相同\n\n成績計算時，以每一科成績乘以該科上課時數為加權成績，將所有科目的加權成績加總，並除以全部科目總時數，即為學生加權平均成績\n\n請設計一個程式，輸入各科的成績、各科加權時數，程式運算後輸出加權總分、加權平均、等弟。\n\n第一行輸入N，代表該科共有N科考試成績\n\n第二行依序輸入N筆各科成績，各科成績之間以空白間隔\n\n第三行依序輸入N筆各科對應加權時數，各科加權時數之間以空白間隔\n\n計算全部加權總分，加權平均成績以四捨五入取整數\n\n如果平均分數大於等於 80，就是「A」等第，小於80大於等於70則是「B」等第，小於70大於等於60則是「C」等第，否則是「D」等第。\n\n程式輸出加權總分、加權平均、等弟。\n\n這題可以訓練你如何處理多筆資料的加總、平均計算，並搭配條件判斷。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n3\n80 70 90\n1 2 1\n\n310\n78\nB\n\n第一行輸入3，表示後面會有3科成績輸入\n\n第二行輸入各科原始成績80 70 90\n\n第三行輸入各科加權時數1 2 1\n\n程式運算輸出加權總分310、平均78、等第B\n\n6\n50 41 60 55 70 65\n\n668\n56\nD\n\n第一行輸入6，表示後面會有6科成績輸入\n\n第二行輸入各科原始成績50 41 60 55 70 65\n\n第三行輸入各科加權時數1 3 3 2 2 1\n\n程式運算輸出加權總分668、平均56、等第D",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "題目：加權成績計算\n\n題目說明\n\n大明綜合高中辦理考試，不同科系考試科目數量、每周上課時數不一定相同\n\n成績計算時，以每一科成績乘以該科上課時數為加權成績，將所有科目的加權成績加總，並除以全部科目總時數，即為學生加權平均成績\n\n請設計一個程式，輸入各科的成績、各科加權時數，程式運算後輸出加權總分、加權平均、等弟。\n\n第一行輸入N，代表該科共有N科考試成績\n\n第二行依序輸入N筆各科成績，各科成績之間以空白間隔\n\n第三行依序輸入N筆各科對應加權時數，各科加權時數之間以空白間隔\n\n計算全部加權總分，加權平均成績以四捨五入取整數\n\n如果平均分數大於等於 80，就是「A」等第，小於80大於等於70則是「B」等第，小於70大於等於60則是「C」等第，否則是「D」等第。\n\n程式輸出加權總分、加權平均、等弟。\n\n這題可以訓練你如何處理多筆資料的加總、平均計算，並搭配條件判斷。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n3\n80 70 90\n1 2 1\n\n310\n78\nB\n\n第一行輸入3，表示後面會有3科成績輸入\n\n第二行輸入各科原始成績80 70 90\n\n第三行輸入各科加權時數1 2 1\n\n程式運算輸出加權總分310、平均78、等第B\n\n6\n50 41 60 55 70 65\n\n668\n56\nD\n\n第一行輸入6，表示後面會有6科成績輸入\n\n第二行輸入各科原始成績50 41 60 55 70 65\n\n第三行輸入各科加權時數1 3 3 2 2 1\n\n程式運算輸出加權總分668、平均56、等第D",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "3\n80 70 90\n1 2 1",
          "output": "310\n78\nB",
          "explanation": "第一行輸入3，表示後面會有3科成績輸入\n第二行輸入各科原始成績80 70 90\n第三行輸入各科加權時數1 2 1\n程式運算輸出加權總分310、平均78、等第B"
        },
        {
          "input": "6\n50 41 60 55 70 65",
          "output": "668\n56\nD",
          "explanation": "第一行輸入6，表示後面會有6科成績輸入\n第二行輸入各科原始成績50 41 60 55 70 65\n第三行輸入各科加權時數1 3 3 2 2 1\n程式運算輸出加權總分668、平均56、等第D"
        }
      ],
      "testCases": [
        {
          "input": "1\n80\n3",
          "expectedOutput": "240 80 A",
          "output": "240 80 A",
          "score": 10,
          "hidden": false
        },
        {
          "input": "6\n50 41 60 55 70 65\n1 3 3 2 2 1",
          "expectedOutput": "668 56 D",
          "output": "668 56 D",
          "score": 10,
          "hidden": false
        },
        {
          "input": "5\n80 70 75 85 90\n1 1 3 2 1",
          "expectedOutput": "635 79 B",
          "output": "635 79 B",
          "score": 10,
          "hidden": false
        },
        {
          "input": "3\n55 90 99\n2 3 3",
          "expectedOutput": "677 85 A",
          "output": "677 85 A",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-11-0",
      "title": "計算字元出現次數",
      "problemTitle": "計算字元出現次數",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：計算字元出現次數\n\n題目說明\n\n請設計程式，輸入一個字串，並輸入一個英文字母輸出該字母在字串中出現的次數。\n\n這樣的練習可以訓練你操作字串與統計。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\nbanana\na\n\n3\n\n第一行輸入banana\n\n第二行輸入字元a\n\n程式運算比對a出現3次\n\n程式輸出3\n\nstudent\nt\n\n2\n\n第一行輸入student\n\n第二行輸入字元t\n\n程式運算比對t出現2次\n\n程式輸出2",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "題目：計算字元出現次數\n\n題目說明\n\n請設計程式，輸入一個字串，並輸入一個英文字母輸出該字母在字串中出現的次數。\n\n這樣的練習可以訓練你操作字串與統計。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\nbanana\na\n\n3\n\n第一行輸入banana\n\n第二行輸入字元a\n\n程式運算比對a出現3次\n\n程式輸出3\n\nstudent\nt\n\n2\n\n第一行輸入student\n\n第二行輸入字元t\n\n程式運算比對t出現2次\n\n程式輸出2",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "banana\na",
          "output": "3",
          "explanation": "第一行輸入banana\n第二行輸入字元a\n程式運算比對a出現3次\n程式輸出3"
        },
        {
          "input": "student\nt",
          "output": "2",
          "explanation": "第一行輸入student\n第二行輸入字元t\n程式運算比對t出現2次\n程式輸出2"
        }
      ],
      "testCases": [
        {
          "input": "Goodmoning\no",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        },
        {
          "input": "ChaiYiCity\ni",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        },
        {
          "input": "announcement\nn",
          "expectedOutput": "4",
          "output": "4",
          "score": 10,
          "hidden": false
        },
        {
          "input": "experimen\ne",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-11-1",
      "title": "計算字元出現最多次數",
      "problemTitle": "計算字元出現最多次數",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：計算字元出現最多的次數\n\n題目說明\n\n請設計程式，輸入一字串由小寫英文字母組合，長度1~50間的字串\n\n程式會統計該字串的字母中，出現最多的次數。\n\n這樣的練習可以訓練你循環計數迴圈與字串統計。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\nbanana\n\n3\n\n第一行輸入banana\n\n程式運算比對，出現最多為a，共出現3次\n\n程式輸出3\n\nstudent\n\n2\n\n第一行輸入student\n\n程式運算比對，出現最多為t，共出現2次\n\n程式輸出2\n\nspider\n\n1\n\n第一行輸入spider\n\n程式運算比對，全部字母都只出現1次\n\n程式輸出1",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "題目：計算字元出現最多的次數\n\n題目說明\n\n請設計程式，輸入一字串由小寫英文字母組合，長度1~50間的字串\n\n程式會統計該字串的字母中，出現最多的次數。\n\n這樣的練習可以訓練你循環計數迴圈與字串統計。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\nbanana\n\n3\n\n第一行輸入banana\n\n程式運算比對，出現最多為a，共出現3次\n\n程式輸出3\n\nstudent\n\n2\n\n第一行輸入student\n\n程式運算比對，出現最多為t，共出現2次\n\n程式輸出2\n\nspider\n\n1\n\n第一行輸入spider\n\n程式運算比對，全部字母都只出現1次\n\n程式輸出1",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "banana",
          "output": "3",
          "explanation": "第一行輸入banana\n程式運算比對，出現最多為a，共出現3次\n程式輸出3"
        },
        {
          "input": "student",
          "output": "2",
          "explanation": "第一行輸入student\n程式運算比對，出現最多為t，共出現2次\n程式輸出2"
        },
        {
          "input": "spider",
          "output": "1",
          "explanation": "第一行輸入spider\n程式運算比對，全部字母都只出現1次\n程式輸出1"
        }
      ],
      "testCases": [
        {
          "input": "goodmoning",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        },
        {
          "input": "ChaiYiCity",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        },
        {
          "input": "announment",
          "expectedOutput": "4",
          "output": "4",
          "score": 10,
          "hidden": false
        },
        {
          "input": "experimen",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        },
        {
          "input": "junior",
          "expectedOutput": "1",
          "output": "1",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-12-0",
      "title": "簡易密碼轉換",
      "problemTitle": "簡易密碼轉換",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：簡易密碼轉換\n\n題目說明\n\n小明設計了一種簡單的密碼環密碼規則：將每個字母向後移二個字母（z 變 b）。\n\n密碼環：abcdefghijklmnopqrstuvwxyz\n\n請寫一個程式，輸入一個英文單字，輸出轉換後的字串。\n\n這樣的練習訓練你字元處理與條件轉換。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\nbanana\n\ndcpcpc\n\n第一行輸入banana\n\n程式運算，將字串往後移2個位置加密\n\n程式輸出dcpcpc\n\nstudent\n\nuvwfgpv\n\n第一行輸入student\n\n程式運算，將字串往後移2個位置加密\n\n程式輸出uvwfgpv",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "題目：簡易密碼轉換\n\n題目說明\n\n小明設計了一種簡單的密碼環密碼規則：將每個字母向後移二個字母（z 變 b）。\n\n密碼環：abcdefghijklmnopqrstuvwxyz\n\n請寫一個程式，輸入一個英文單字，輸出轉換後的字串。\n\n這樣的練習訓練你字元處理與條件轉換。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\nbanana\n\ndcpcpc\n\n第一行輸入banana\n\n程式運算，將字串往後移2個位置加密\n\n程式輸出dcpcpc\n\nstudent\n\nuvwfgpv\n\n第一行輸入student\n\n程式運算，將字串往後移2個位置加密\n\n程式輸出uvwfgpv",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "banana",
          "output": "dcpcpc",
          "explanation": "第一行輸入banana\n程式運算，將字串往後移2個位置加密\n程式輸出dcpcpc"
        },
        {
          "input": "student",
          "output": "uvwfgpv",
          "explanation": "第一行輸入student\n程式運算，將字串往後移2個位置加密\n程式輸出uvwfgpv"
        }
      ],
      "testCases": [
        {
          "input": "goodmoning",
          "expectedOutput": "iqqfoqpkpi",
          "output": "iqqfoqpkpi",
          "score": 10,
          "hidden": false
        },
        {
          "input": "chaiyicity",
          "expectedOutput": "ejckakekva",
          "output": "ejckakekva",
          "score": 10,
          "hidden": false
        },
        {
          "input": "announcement",
          "expectedOutput": "cppqwpegogpv",
          "output": "cppqwpegogpv",
          "score": 10,
          "hidden": false
        },
        {
          "input": "experimen",
          "expectedOutput": "gzrgtkogp",
          "output": "gzrgtkogp",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-12-1",
      "title": "動態密碼轉換",
      "problemTitle": "動態密碼轉換",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：動態密碼轉換\n\n題目說明\n\n小明設計了一種英文字元密碼環編碼規則：\n\n密碼環為『abcdefghijklmnopqrstuvwxyz0123456789』\n\n第一行輸入數字N(N介於0~36)，N為編碼位移值\n\n編碼時，待編碼字串每個字元都按照密碼環『往前』移動N個位置\n\n如果轉換後密碼超過密碼環最後一個字元9，則從回前面a繼續接回密碼環\n\n請寫一個程式，輸入一個英文單字，程式輸出依照編碼規則轉換後的密碼字串。\n\n這樣的練習訓練你字元處理與條件轉換。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n2\nbanana\n\n98l8l8\n\n第一行輸入2，表示編碼時要往後前2個位置\n\n第二行輸入banana表示待編碼字串為banana\n\n程式運算，將字串往後移2個位置加密\n\n程式輸出98l8l8\n\n10\nstudent\n\nijk34dj\n\n第一行輸入10，表示編碼時要往後前10個位置\n\n第二行輸入student表示待編碼字串為student\n\n程式運算，將字串往後移10個位置加密\n\n程式輸出ijk34dj",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "題目：動態密碼轉換\n\n題目說明\n\n小明設計了一種英文字元密碼環編碼規則：\n\n密碼環為『abcdefghijklmnopqrstuvwxyz0123456789』\n\n第一行輸入數字N(N介於0~36)，N為編碼位移值\n\n編碼時，待編碼字串每個字元都按照密碼環『往前』移動N個位置\n\n如果轉換後密碼超過密碼環最後一個字元9，則從回前面a繼續接回密碼環\n\n請寫一個程式，輸入一個英文單字，程式輸出依照編碼規則轉換後的密碼字串。\n\n這樣的練習訓練你字元處理與條件轉換。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n2\nbanana\n\n98l8l8\n\n第一行輸入2，表示編碼時要往後前2個位置\n\n第二行輸入banana表示待編碼字串為banana\n\n程式運算，將字串往後移2個位置加密\n\n程式輸出98l8l8\n\n10\nstudent\n\nijk34dj\n\n第一行輸入10，表示編碼時要往後前10個位置\n\n第二行輸入student表示待編碼字串為student\n\n程式運算，將字串往後移10個位置加密\n\n程式輸出ijk34dj",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "2\nbanana",
          "output": "98l8l8",
          "explanation": "第一行輸入2，表示編碼時要往後前2個位置\n第二行輸入banana表示待編碼字串為banana\n程式運算，將字串往後移2個位置加密\n程式輸出98l8l8"
        },
        {
          "input": "10\nstudent",
          "output": "ijk34dj",
          "explanation": "第一行輸入10，表示編碼時要往後前10個位置\n第二行輸入student表示待編碼字串為student\n程式運算，將字串往後移10個位置加密\n程式輸出ijk34dj"
        }
      ],
      "testCases": [
        {
          "input": "12\ngoodmoning",
          "expectedOutput": "4cc1acb6b4",
          "output": "4cc1acb6b4",
          "score": 10,
          "hidden": false
        },
        {
          "input": "29\nchaiyicity",
          "expectedOutput": "johp5pjp05",
          "output": "johp5pjp05",
          "score": 10,
          "hidden": false
        },
        {
          "input": "9\nannouncement",
          "expectedOutput": "1eefle35d5ek",
          "output": "1eefle35d5ek",
          "score": 10,
          "hidden": false
        },
        {
          "input": "0\nexperimen",
          "expectedOutput": "experimen",
          "output": "experimen",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "TYTN-10",
      "title": "Y-2-2-檢查碼",
      "problemTitle": "Y-2-2-檢查碼",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：檢查碼\n\n題目說明\n\n書店會員卡享有購書8折優惠，為避免有人偽造會員卡，書店老闆在卡號中加入檢查碼。\n\n會員卡編號格式為：一個英文字母 + 4個數字 + 1個檢查碼。\n\n英文字母對應的數字如下：\n\nA → 11 B → 13 C → 15 D → 17\n\n若為正確的會員卡號，則 (英文字母對應的數字 + 4個數字 + 檢查碼) 除以 5 的餘數會是 4，其餘情況皆為不正確。\n\n例如：\n\nB20135 = 13+2+0+1+3+5 = 24 → 24÷5=4餘4 → 正確會員卡\n\nA15274 = 11+1+5+2+7+4 = 30 → 30÷5=6餘0 → 不正確會員卡\n\n請寫一個程式判斷會員卡號是否正確，若正確輸出 yes，否則輸出 no。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\nC20351\n\nno\n\nC20351 = 15+2+0+3+5+1 = 26\n\n26÷5 = 5餘1 → 不正確會員卡。\n\nD15713\n\nyes\n\nD15713 = 17+1+5+7+1+3 = 34\n\n34÷5 = 6餘4 → 正確會員卡。",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "題目：檢查碼\n\n題目說明\n\n書店會員卡享有購書8折優惠，為避免有人偽造會員卡，書店老闆在卡號中加入檢查碼。\n\n會員卡編號格式為：一個英文字母 + 4個數字 + 1個檢查碼。\n\n英文字母對應的數字如下：\n\nA → 11 B → 13 C → 15 D → 17\n\n若為正確的會員卡號，則 (英文字母對應的數字 + 4個數字 + 檢查碼) 除以 5 的餘數會是 4，其餘情況皆為不正確。\n\n例如：\n\nB20135 = 13+2+0+1+3+5 = 24 → 24÷5=4餘4 → 正確會員卡\n\nA15274 = 11+1+5+2+7+4 = 30 → 30÷5=6餘0 → 不正確會員卡\n\n請寫一個程式判斷會員卡號是否正確，若正確輸出 yes，否則輸出 no。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\nC20351\n\nno\n\nC20351 = 15+2+0+3+5+1 = 26\n\n26÷5 = 5餘1 → 不正確會員卡。\n\nD15713\n\nyes\n\nD15713 = 17+1+5+7+1+3 = 34\n\n34÷5 = 6餘4 → 正確會員卡。",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "C20351",
          "output": "no",
          "explanation": "C20351 = 15+2+0+3+5+1 = 26\n26÷5 = 5餘1 → 不正確會員卡。"
        },
        {
          "input": "D15713",
          "output": "yes",
          "explanation": "D15713 = 17+1+5+7+1+3 = 34\n34÷5 = 6餘4 → 正確會員卡。"
        }
      ],
      "testCases": [
        {
          "input": "C20351",
          "expectedOutput": "no",
          "output": "no",
          "score": 10,
          "hidden": false
        },
        {
          "input": "D15713",
          "expectedOutput": "yes",
          "output": "yes",
          "score": 10,
          "hidden": false
        },
        {
          "input": "A40244",
          "expectedOutput": "no",
          "output": "no",
          "score": 10,
          "hidden": false
        },
        {
          "input": "B99994",
          "expectedOutput": "no",
          "output": "no",
          "score": 10,
          "hidden": false
        },
        {
          "input": "A22146",
          "expectedOutput": "no",
          "output": "no",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "W4-01",
      "title": "數位顯示器",
      "problemTitle": "數位顯示器",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：數位顯示器\n\n題目說明\n\n七段顯示器是一種常見的數字顯示裝置，由 7 條 LED 燈條組成，可用來顯示數字 0~9。\n\n每個數字所需點亮的 LED 燈條數量如下：\n\n0→6條、1→2條、2→5條、3→5條、4→4條、5→5條、6→6條、7→3條、8→7條、9→6條。\n\n現在給定 N 條可用的 LED 燈條，請你使用這些燈條組成一個「數字（可為雙位數）」，並且必須符合以下規則：\n\n1. 數字（0~9）最多只能各使用一次（兩位數時十位與個位不能相同）。\n\n2. 組成的數字不可有前導零（除非答案本身就是 0）。\n\n3. 組成的數字最多只能有 2 位（0~99）。\n\n請設計一個程式，找出在符合上述條件下「剛好用完所有 N 條 LED 燈條」時，可以組成的最大值。\n\n若無法用 1 位數或 2 位數剛好用完所有 N 條 LED 燈條，請輸出 -1。\n\n【",
      "inputDescription": "】\n\n一行輸入一個整數 N（2 ≤ N ≤ 30），代表可用的 LED 燈條數。\n\n【",
      "outputDescription": "】\n\n一行輸出可組成的最大值（最大值 < 100），若不存在則輸出 -1。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n3\n\n7\n\n3 條燈條可以組成數字 7（需要 3 條）。\n\n7\n\n74\n\n7(3條)+4(4條)=7。可組成 74 或 47，最大為 74。",
      "statement": {
        "description": "題目：數位顯示器\n\n題目說明\n\n七段顯示器是一種常見的數字顯示裝置，由 7 條 LED 燈條組成，可用來顯示數字 0~9。\n\n每個數字所需點亮的 LED 燈條數量如下：\n\n0→6條、1→2條、2→5條、3→5條、4→4條、5→5條、6→6條、7→3條、8→7條、9→6條。\n\n現在給定 N 條可用的 LED 燈條，請你使用這些燈條組成一個「數字（可為雙位數）」，並且必須符合以下規則：\n\n1. 數字（0~9）最多只能各使用一次（兩位數時十位與個位不能相同）。\n\n2. 組成的數字不可有前導零（除非答案本身就是 0）。\n\n3. 組成的數字最多只能有 2 位（0~99）。\n\n請設計一個程式，找出在符合上述條件下「剛好用完所有 N 條 LED 燈條」時，可以組成的最大值。\n\n若無法用 1 位數或 2 位數剛好用完所有 N 條 LED 燈條，請輸出 -1。\n\n【",
        "input": "】\n\n一行輸入一個整數 N（2 ≤ N ≤ 30），代表可用的 LED 燈條數。\n\n【",
        "output": "】\n\n一行輸出可組成的最大值（最大值 < 100），若不存在則輸出 -1。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n3\n\n7\n\n3 條燈條可以組成數字 7（需要 3 條）。\n\n7\n\n74\n\n7(3條)+4(4條)=7。可組成 74 或 47，最大為 74。"
      },
      "examples": [
        {
          "input": "3",
          "output": "7",
          "explanation": "3 條燈條可以組成數字 7（需要 3 條）。"
        },
        {
          "input": "7",
          "output": "74",
          "explanation": "7(3條)+4(4條)=7。可組成 74 或 47，最大為 74。"
        }
      ],
      "testCases": [
        {
          "input": "3",
          "expectedOutput": "7",
          "output": "7",
          "score": 10,
          "hidden": false
        },
        {
          "input": "7",
          "expectedOutput": "74",
          "output": "74",
          "score": 15,
          "hidden": false
        },
        {
          "input": "6",
          "expectedOutput": "41",
          "output": "41",
          "score": 20,
          "hidden": false
        },
        {
          "input": "8",
          "expectedOutput": "91",
          "output": "91",
          "score": 25,
          "hidden": false
        },
        {
          "input": "14",
          "expectedOutput": "-1",
          "output": "-1",
          "score": 30,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "W5-02",
      "title": "5進位解碼",
      "problemTitle": "5進位解碼",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：5進位解碼\n\n題目說明\n\n程式設計社的入社考題是一串神秘代碼。代碼由 A, B, C, D, E 五個字母組成，這其實是一個「5進位」數字系統：\nA=0, B=1, C=2, D=3, E=4，\n例如密碼 BC 代表 5進位的 12，換算成 10 進位就是 1 × 5 + 2 = 7。請編寫程式將密碼解碼為 10 進位數字。\n\n1. 輸入密碼長度 L 與密碼內容（由A-E組成）。\n\n2. 權重計算：最右邊位數是 5的0次方(任何數的0次方為1)，左邊一位是 5的1次方，以此類推。\n\n3. 將每個字母轉換為對應數值後，計算總和。",
      "inputDescription": "第一行：整數 L。\n\n第二行：L 個字元（以空格分隔，如 B C）。",
      "outputDescription": "一個整數（10 進位數值）。\n\n範例一\n\n輸入\n\n2\nB C\n\n輸出\n\n7\n\n範例說明\n\nB=1, C=2。\n\n1 × 5 + 2 = 7。\n\n範例二\n\n輸入\n\n3\nB A E\n\n輸出\n\n29\n\n範例說明\n\nB=1, A=0, E=4。\n\n1 × 25 + 0 × 5 + 4 × 1 = 29。",
      "statement": {
        "description": "題目：5進位解碼\n\n題目說明\n\n程式設計社的入社考題是一串神秘代碼。代碼由 A, B, C, D, E 五個字母組成，這其實是一個「5進位」數字系統：\nA=0, B=1, C=2, D=3, E=4，\n例如密碼 BC 代表 5進位的 12，換算成 10 進位就是 1 × 5 + 2 = 7。請編寫程式將密碼解碼為 10 進位數字。\n\n1. 輸入密碼長度 L 與密碼內容（由A-E組成）。\n\n2. 權重計算：最右邊位數是 5的0次方(任何數的0次方為1)，左邊一位是 5的1次方，以此類推。\n\n3. 將每個字母轉換為對應數值後，計算總和。",
        "input": "第一行：整數 L。\n\n第二行：L 個字元（以空格分隔，如 B C）。",
        "output": "一個整數（10 進位數值）。\n\n範例一\n\n輸入\n\n2\nB C\n\n輸出\n\n7\n\n範例說明\n\nB=1, C=2。\n\n1 × 5 + 2 = 7。\n\n範例二\n\n輸入\n\n3\nB A E\n\n輸出\n\n29\n\n範例說明\n\nB=1, A=0, E=4。\n\n1 × 25 + 0 × 5 + 4 × 1 = 29。"
      },
      "examples": [
        {
          "input": "2\nB C",
          "output": "7",
          "explanation": "B=1, C=2。\n1 × 5 + 2 = 7。"
        },
        {
          "input": "3\nB A E",
          "output": "29",
          "explanation": "B=1, A=0, E=4。\n1 × 25 + 0 × 5 + 4 × 1 = 29。"
        }
      ],
      "testCases": [
        {
          "input": "1\nA",
          "expectedOutput": "0",
          "output": "0",
          "score": 10,
          "hidden": false
        },
        {
          "input": "2\nE E",
          "expectedOutput": "24",
          "output": "24",
          "score": 15,
          "hidden": false
        },
        {
          "input": "3\nB A A",
          "expectedOutput": "25",
          "output": "25",
          "score": 20,
          "hidden": false
        },
        {
          "input": "4\nB A A A",
          "expectedOutput": "125",
          "output": "125",
          "score": 25,
          "hidden": false
        },
        {
          "input": "5\nC D E A B",
          "expectedOutput": "1726",
          "output": "1726",
          "score": 30,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "W7-01",
      "title": "校園密室逃脫-書架的密碼",
      "problemTitle": "校園密室逃脫-書架的密碼",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：校園密室逃脫-書架的密碼(6-1)\n問題描述\n\n傳說在校園圖書館的深處，隱藏著一間百年前首任校長留下的「智慧密室」。今年校慶，學生會利用最新的 AR 技術重現了這個傳說，設計了四道關卡。只有解開所有謎題的小隊，才能獲得象徵最高榮譽的「智慧之鑰」。你的小隊現在正站在密室的入口。\n\n第一道關卡是一扇巨大的電子鐵門。門鎖的螢幕上並沒有數字鍵盤，只有一串閃爍的、由 0 與 1 組成的符號序列。門邊的銘牌刻著一行字：「只有通曉機器語言的人，才能將二元的虛幻轉化為十進的真實。」這顯然是一個二進位轉十進位的謎題。請將螢幕上的二進位字串解碼為十進位數字，輸入系統以開啟大門。",
      "inputDescription": "第一行：一個字串 S（只包含 0 與 1）。",
      "outputDescription": "第一行：一個整數，代表轉換後的十進位數值。\n\n使用者輸入\n輸出\n範例說明\n\n101\n5\n\n1x4 + 0x2 + 1x1 = 5\n\n1111\n15\n\n8 + 4 + 2 + 1 = 15",
      "statement": {
        "description": "題目：校園密室逃脫-書架的密碼(6-1)\n問題描述\n\n傳說在校園圖書館的深處，隱藏著一間百年前首任校長留下的「智慧密室」。今年校慶，學生會利用最新的 AR 技術重現了這個傳說，設計了四道關卡。只有解開所有謎題的小隊，才能獲得象徵最高榮譽的「智慧之鑰」。你的小隊現在正站在密室的入口。\n\n第一道關卡是一扇巨大的電子鐵門。門鎖的螢幕上並沒有數字鍵盤，只有一串閃爍的、由 0 與 1 組成的符號序列。門邊的銘牌刻著一行字：「只有通曉機器語言的人，才能將二元的虛幻轉化為十進的真實。」這顯然是一個二進位轉十進位的謎題。請將螢幕上的二進位字串解碼為十進位數字，輸入系統以開啟大門。",
        "input": "第一行：一個字串 S（只包含 0 與 1）。",
        "output": "第一行：一個整數，代表轉換後的十進位數值。\n\n使用者輸入\n輸出\n範例說明\n\n101\n5\n\n1x4 + 0x2 + 1x1 = 5\n\n1111\n15\n\n8 + 4 + 2 + 1 = 15"
      },
      "examples": [
        {
          "input": "101",
          "output": "5",
          "explanation": "1x4 + 0x2 + 1x1 = 5"
        },
        {
          "input": "1111",
          "output": "15",
          "explanation": "8 + 4 + 2 + 1 = 15"
        }
      ],
      "testCases": [
        {
          "input": "10",
          "expectedOutput": "2",
          "output": "2",
          "score": 10,
          "hidden": false
        },
        {
          "input": "110",
          "expectedOutput": "6",
          "output": "6",
          "score": 15,
          "hidden": false
        },
        {
          "input": "1000",
          "expectedOutput": "8",
          "output": "8",
          "score": 20,
          "hidden": false
        },
        {
          "input": "11011",
          "expectedOutput": "27",
          "output": "27",
          "score": 25,
          "hidden": false
        },
        {
          "input": "1111101000",
          "expectedOutput": "1000",
          "output": "1000",
          "score": 30,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "cycjunior-002",
      "title": "5進位解碼",
      "problemTitle": "5進位解碼",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：5進位解碼\n\n題目說明\n\n程式設計社的入社考題是一串神秘代碼。代碼由 A, B, C, D, E 五個字母組成，這其實是一個「5進位」數字系統：\nA=0, B=1, C=2, D=3, E=4，\n例如密碼 BC 代表 5進位的 12，換算成 10 進位就是 1 × 5 + 2 = 7。請編寫程式將密碼解碼為 10 進位數字。\n\n1. 輸入密碼長度 L 與密碼內容（由A-E組成）。\n\n2. 權重計算：最右邊位數是 5的0次方(任何數的0次方為1)，左邊一位是 5的1次方，以此類推。\n\n3. 將每個字母轉換為對應數值後，計算總和。",
      "inputDescription": "第一行：整數 L。\n\n第二行：L 個字元（以空格分隔，如 B C）。",
      "outputDescription": "一個整數（10 進位數值）。\n\n範例一\n\n輸入\n\n2\nB C\n\n輸出\n\n7\n\n範例說明\n\nB=1, C=2。\n\n1 × 5 + 2 = 7。\n\n範例二\n\n輸入\n\n3\nB A E\n\n輸出\n\n29\n\n範例說明\n\nB=1, A=0, E=4。\n\n1 × 25 + 0 × 5 + 4 × 1 = 29。",
      "statement": {
        "description": "題目：5進位解碼\n\n題目說明\n\n程式設計社的入社考題是一串神秘代碼。代碼由 A, B, C, D, E 五個字母組成，這其實是一個「5進位」數字系統：\nA=0, B=1, C=2, D=3, E=4，\n例如密碼 BC 代表 5進位的 12，換算成 10 進位就是 1 × 5 + 2 = 7。請編寫程式將密碼解碼為 10 進位數字。\n\n1. 輸入密碼長度 L 與密碼內容（由A-E組成）。\n\n2. 權重計算：最右邊位數是 5的0次方(任何數的0次方為1)，左邊一位是 5的1次方，以此類推。\n\n3. 將每個字母轉換為對應數值後，計算總和。",
        "input": "第一行：整數 L。\n\n第二行：L 個字元（以空格分隔，如 B C）。",
        "output": "一個整數（10 進位數值）。\n\n範例一\n\n輸入\n\n2\nB C\n\n輸出\n\n7\n\n範例說明\n\nB=1, C=2。\n\n1 × 5 + 2 = 7。\n\n範例二\n\n輸入\n\n3\nB A E\n\n輸出\n\n29\n\n範例說明\n\nB=1, A=0, E=4。\n\n1 × 25 + 0 × 5 + 4 × 1 = 29。"
      },
      "examples": [
        {
          "input": "2\nB C",
          "output": "7",
          "explanation": "B=1, C=2。\n1 × 5 + 2 = 7。"
        },
        {
          "input": "3\nB A E",
          "output": "29",
          "explanation": "B=1, A=0, E=4。\n1 × 25 + 0 × 5 + 4 × 1 = 29。"
        }
      ],
      "testCases": [
        {
          "input": "1\nA",
          "expectedOutput": "0",
          "output": "0",
          "score": 10,
          "hidden": false
        },
        {
          "input": "2\nE E",
          "expectedOutput": "24",
          "output": "24",
          "score": 15,
          "hidden": false
        },
        {
          "input": "3\nB A A",
          "expectedOutput": "25",
          "output": "25",
          "score": 20,
          "hidden": false
        },
        {
          "input": "4\nB A A A",
          "expectedOutput": "125",
          "output": "125",
          "score": 25,
          "hidden": false
        },
        {
          "input": "5\nC D E A B",
          "expectedOutput": "1726",
          "output": "1726",
          "score": 30,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "cyjunior-002",
      "title": "神秘的古代石板",
      "problemTitle": "神秘的古代石板",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：神秘的古代石板\n題目說明\n\n考古社的社員們在整理學校老舊圖書館的地下倉庫時，意外在一個積滿灰塵的角落發現了一塊斷裂的古代石板。石板上刻著一串長得驚人的數字，根據碳十四定年法推測，這可能與百年前一位精通術數的隱士有關。\n\n隨同石板出土的還有一卷泛黃的羊皮紙，上面記載著開啟地下密室的線索：「當數字之河能同時通過『五行之神』與『十一星宿』的試煉時，真理之門將會開啟。」\n\n身為資訊社社長的你被緊急找來協助解謎。羊皮紙下方的註解解釋了試煉的規則：\n\n1. 五行之神的試煉：根據古老的五行方位，數字的尾端必須歸於土或水，這意味著該數字必須是 5 的倍數（個位數為 0 或 5）。\n\n2. 十一星宿的試煉：這是一個複雜的星象算法。你需要將數字中位於「奇數位置」的數字總和，減去位於「偶數位置」的數字總和。如果這個差值能夠被 11 整除（包含 0），才算通過試煉。（注意：若相減後為負數，必須不斷加上 11 的週期，直到轉為非負數後再進行判斷）。\n\n由於石板上的數字極長（甚至超過 23 位數），一般的計算機早已無法處理。請撰寫程式來驗證這串數字是否能同時解開這兩道封印。\n\nNote:\n\nScratch與 Blockly 積木運算大於16位數字時已無法精確運算，因此輸入的數字字串最後方會強制加上一個英文字母 a (例如 12345a)， 請將其視為字串處理，讀取時請記得忽略最後一個字元。",
      "inputDescription": "第一行：一個字串(包含後置的英文字母a)，代表石板上的超長整數\n\n輸入格式\n\n第一行：兩個整數（0 或 1），中間以空格分隔，1代表「是」，0代表「非」。\n\n第一個數字代表是否為 5 的倍數，第二個代表是否為 11 的倍數。\n\n使用者輸入\n輸出\n範例說明\n\n55a\n1 1\n\n尾數5 (是5的倍數)。\n\n奇位和5 - 偶位和5 = 0 (是11的倍數)。\n\n1234a\n0 0\n\n尾數4 (非5的倍數)。\n\n奇位和4 - 偶位和6 = -2 (非11的倍數)。\n\n1651651651651651651651650a\n1 1\n尾數0 (是5的倍數)。\n\n奇位和36 - 偶位和36 = 0 (是11的倍數)。",
      "outputDescription": "",
      "statement": {
        "description": "題目：神秘的古代石板\n題目說明\n\n考古社的社員們在整理學校老舊圖書館的地下倉庫時，意外在一個積滿灰塵的角落發現了一塊斷裂的古代石板。石板上刻著一串長得驚人的數字，根據碳十四定年法推測，這可能與百年前一位精通術數的隱士有關。\n\n隨同石板出土的還有一卷泛黃的羊皮紙，上面記載著開啟地下密室的線索：「當數字之河能同時通過『五行之神』與『十一星宿』的試煉時，真理之門將會開啟。」\n\n身為資訊社社長的你被緊急找來協助解謎。羊皮紙下方的註解解釋了試煉的規則：\n\n1. 五行之神的試煉：根據古老的五行方位，數字的尾端必須歸於土或水，這意味著該數字必須是 5 的倍數（個位數為 0 或 5）。\n\n2. 十一星宿的試煉：這是一個複雜的星象算法。你需要將數字中位於「奇數位置」的數字總和，減去位於「偶數位置」的數字總和。如果這個差值能夠被 11 整除（包含 0），才算通過試煉。（注意：若相減後為負數，必須不斷加上 11 的週期，直到轉為非負數後再進行判斷）。\n\n由於石板上的數字極長（甚至超過 23 位數），一般的計算機早已無法處理。請撰寫程式來驗證這串數字是否能同時解開這兩道封印。\n\nNote:\n\nScratch與 Blockly 積木運算大於16位數字時已無法精確運算，因此輸入的數字字串最後方會強制加上一個英文字母 a (例如 12345a)， 請將其視為字串處理，讀取時請記得忽略最後一個字元。",
        "input": "第一行：一個字串(包含後置的英文字母a)，代表石板上的超長整數\n\n輸入格式\n\n第一行：兩個整數（0 或 1），中間以空格分隔，1代表「是」，0代表「非」。\n\n第一個數字代表是否為 5 的倍數，第二個代表是否為 11 的倍數。\n\n使用者輸入\n輸出\n範例說明\n\n55a\n1 1\n\n尾數5 (是5的倍數)。\n\n奇位和5 - 偶位和5 = 0 (是11的倍數)。\n\n1234a\n0 0\n\n尾數4 (非5的倍數)。\n\n奇位和4 - 偶位和6 = -2 (非11的倍數)。\n\n1651651651651651651651650a\n1 1\n尾數0 (是5的倍數)。\n\n奇位和36 - 偶位和36 = 0 (是11的倍數)。",
        "output": ""
      },
      "examples": [
        {
          "input": "55a",
          "output": "1 1",
          "explanation": "尾數5                  (是5的倍數)。\n奇位和5 - 偶位和5 = 0   (是11的倍數)。"
        },
        {
          "input": "1234a",
          "output": "0 0",
          "explanation": "尾數4                  (非5的倍數)。\n奇位和4 - 偶位和6 = -2  (非11的倍數)。"
        },
        {
          "input": "1651651651651651651651650a",
          "output": "1 1",
          "explanation": "尾數0                  (是5的倍數)。\n奇位和36 - 偶位和36 = 0 (是11的倍數)。"
        }
      ],
      "testCases": [
        {
          "input": "35a",
          "expectedOutput": "1 0",
          "output": "1 0",
          "score": 10,
          "hidden": false
        },
        {
          "input": "121a",
          "expectedOutput": "0 1",
          "output": "0 1",
          "score": 15,
          "hidden": false
        },
        {
          "input": "123a",
          "expectedOutput": "0 0",
          "output": "0 0",
          "score": 20,
          "hidden": false
        },
        {
          "input": "55555555555555555555555555a",
          "expectedOutput": "1 1",
          "output": "1 1",
          "score": 25,
          "hidden": false
        },
        {
          "input": "5060506050605060506050605060a",
          "expectedOutput": "1 1",
          "output": "1 1",
          "score": 30,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "cyjunior-006",
      "title": "校園密室逃脫-書架的密碼(6-1)",
      "problemTitle": "校園密室逃脫-書架的密碼(6-1)",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：校園密室逃脫-書架的密碼(6-1)\n問題描述\n\n傳說在校園圖書館的深處，隱藏著一間百年前首任校長留下的「智慧密室」。今年校慶，學生會利用最新的 AR 技術重現了這個傳說，設計了四道關卡。只有解開所有謎題的小隊，才能獲得象徵最高榮譽的「智慧之鑰」。你的小隊現在正站在密室的入口。\n\n第一道關卡是一扇巨大的電子鐵門。門鎖的螢幕上並沒有數字鍵盤，只有一串閃爍的、由 0 與 1 組成的符號序列。門邊的銘牌刻著一行字：「只有通曉機器語言的人，才能將二元的虛幻轉化為十進的真實。」這顯然是一個二進位轉十進位的謎題。請將螢幕上的二進位字串解碼為十進位數字，輸入系統以開啟大門。",
      "inputDescription": "第一行：一個字串 S（只包含 0 與 1）。",
      "outputDescription": "第一行：一個整數，代表轉換後的十進位數值。\n\n使用者輸入\n輸出\n範例說明\n\n101\n5\n\n1x4 + 0x2 + 1x1 = 5\n\n1111\n15\n\n8 + 4 + 2 + 1 = 15",
      "statement": {
        "description": "題目：校園密室逃脫-書架的密碼(6-1)\n問題描述\n\n傳說在校園圖書館的深處，隱藏著一間百年前首任校長留下的「智慧密室」。今年校慶，學生會利用最新的 AR 技術重現了這個傳說，設計了四道關卡。只有解開所有謎題的小隊，才能獲得象徵最高榮譽的「智慧之鑰」。你的小隊現在正站在密室的入口。\n\n第一道關卡是一扇巨大的電子鐵門。門鎖的螢幕上並沒有數字鍵盤，只有一串閃爍的、由 0 與 1 組成的符號序列。門邊的銘牌刻著一行字：「只有通曉機器語言的人，才能將二元的虛幻轉化為十進的真實。」這顯然是一個二進位轉十進位的謎題。請將螢幕上的二進位字串解碼為十進位數字，輸入系統以開啟大門。",
        "input": "第一行：一個字串 S（只包含 0 與 1）。",
        "output": "第一行：一個整數，代表轉換後的十進位數值。\n\n使用者輸入\n輸出\n範例說明\n\n101\n5\n\n1x4 + 0x2 + 1x1 = 5\n\n1111\n15\n\n8 + 4 + 2 + 1 = 15"
      },
      "examples": [
        {
          "input": "101",
          "output": "5",
          "explanation": "1x4 + 0x2 + 1x1 = 5"
        },
        {
          "input": "1111",
          "output": "15",
          "explanation": "8 + 4 + 2 + 1 = 15"
        }
      ],
      "testCases": [
        {
          "input": "10",
          "expectedOutput": "2",
          "output": "2",
          "score": 10,
          "hidden": false
        },
        {
          "input": "110",
          "expectedOutput": "6",
          "output": "6",
          "score": 15,
          "hidden": false
        },
        {
          "input": "1000",
          "expectedOutput": "8",
          "output": "8",
          "score": 20,
          "hidden": false
        },
        {
          "input": "11011",
          "expectedOutput": "27",
          "output": "27",
          "score": 25,
          "hidden": false
        },
        {
          "input": "1111101000",
          "expectedOutput": "1000",
          "output": "1000",
          "score": 30,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [
          "有多餘案例"
        ],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "nantoJS-002",
      "title": "熱門影片的流量密碼",
      "problemTitle": "熱門影片的流量密碼",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：熱門影片的流量密碼\n\n題目說明\n\n小雅是一名熱愛經營頻道的國中生YouTuber，她非常在意自己影片的流量趨勢。她從後台導出了過去N天的每日觀看次數紀錄。為了找出最有效的發片節奏與演算法推播規律，她想要找出一段長度剛好為「連續K天」的黃金時期。\n\n在這連續的K天中，所有影片觀看次數的加總必須是所有可能區段中最高的。\n\n例如N=5，5天輸入資料為10 20 30 40 50，K=3，表示要計算連續三天最大值，可能連續3天的區間有：(10+20+30=60)、(20+30+40=90)、(30+40+50=120)，三個區間最大為120。因此輸出120。\n\n請你寫一個程式，幫小雅想一個好方法，快速地算出這段連續K天的最大觀看次數總和。這將有助於她判斷哪一段時間的企劃最受觀眾喜愛。",
      "inputDescription": "第一行：輸入整數N，代表總記錄總天數。\n\n第二行：輸入整數K，代表欲分析的連續天數\n\n第三行：輸入N個整數，代表每天的影片觀看次數紀錄(以半形空格分隔)。",
      "outputDescription": "第一行：輸出一個整數，代表所有連續K天區間中最大的觀看總和。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n8\n\n3\n\n1 5 2 10 8 3 7 2\n\n21\n\n連續3天：(10+8+3)=21 為全域最高。\n\n5\n\n2\n\n10 20 30 20 10\n\n50\n\n連續2天：(20+30)=50 為最高。",
      "statement": {
        "description": "題目：熱門影片的流量密碼\n\n題目說明\n\n小雅是一名熱愛經營頻道的國中生YouTuber，她非常在意自己影片的流量趨勢。她從後台導出了過去N天的每日觀看次數紀錄。為了找出最有效的發片節奏與演算法推播規律，她想要找出一段長度剛好為「連續K天」的黃金時期。\n\n在這連續的K天中，所有影片觀看次數的加總必須是所有可能區段中最高的。\n\n例如N=5，5天輸入資料為10 20 30 40 50，K=3，表示要計算連續三天最大值，可能連續3天的區間有：(10+20+30=60)、(20+30+40=90)、(30+40+50=120)，三個區間最大為120。因此輸出120。\n\n請你寫一個程式，幫小雅想一個好方法，快速地算出這段連續K天的最大觀看次數總和。這將有助於她判斷哪一段時間的企劃最受觀眾喜愛。",
        "input": "第一行：輸入整數N，代表總記錄總天數。\n\n第二行：輸入整數K，代表欲分析的連續天數\n\n第三行：輸入N個整數，代表每天的影片觀看次數紀錄(以半形空格分隔)。",
        "output": "第一行：輸出一個整數，代表所有連續K天區間中最大的觀看總和。\n\n範例格式\n\n使用者輸入\n\n輸出\n\n範例說明\n\n8\n\n3\n\n1 5 2 10 8 3 7 2\n\n21\n\n連續3天：(10+8+3)=21 為全域最高。\n\n5\n\n2\n\n10 20 30 20 10\n\n50\n\n連續2天：(20+30)=50 為最高。"
      },
      "examples": [
        {
          "input": "8\n3\n1 5 2 10 8 3 7 2",
          "output": "21",
          "explanation": "連續3天：(10+8+3)=21 為全域最高。"
        },
        {
          "input": "5\n2\n10 20 30 20 10",
          "output": "50",
          "explanation": "連續2天：(20+30)=50 為最高。"
        }
      ],
      "testCases": [
        {
          "input": "3\n3\n100 200 300",
          "expectedOutput": "600",
          "output": "600",
          "score": 10,
          "hidden": false
        },
        {
          "input": "5\n1\n10 50 20 90 30",
          "expectedOutput": "90",
          "output": "90",
          "score": 15,
          "hidden": false
        },
        {
          "input": "6\n2\n1 2 9 8 6 1",
          "expectedOutput": "17",
          "output": "17",
          "score": 20,
          "hidden": false
        },
        {
          "input": "10\n9\n1 1 5 5 1 1 8 8 1 1",
          "expectedOutput": "31",
          "output": "31",
          "score": 25,
          "hidden": false
        },
        {
          "input": "10\n4\n1 1 5 5 1 1 8 8 1 1",
          "expectedOutput": "18",
          "output": "18",
          "score": 30,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "nantoJS-005",
      "title": "古文明的能量融合",
      "problemTitle": "古文明的能量融合",
      "courseCode": "JSS01",
      "courseName": "字串處理",
      "role": "challenge",
      "difficulty": "L3",
      "blocklyFit": "中",
      "description": "題目：古文明的能量融合\n\n題目說明\n\n考古學家在遺跡中發現了兩塊圓形的能量石板，上面刻著古老的數字代碼。根據解讀，這兩塊石板具有「相位旋轉」的特性。若想啟動遺跡的核心能源必須將這兩股最強的能量數值進行「大數加法」融合，所得的總和就是啟動核心的密碼。 請你編寫程式，根據考古學家輸入的兩塊石板數字，計算出融合後的最終能量數值 。\n\nNote: Scratch與 Blockly 積木運算大於16位的數字時已無法精確運算，因此輸入及輸出的數字字串最後方會強制加上一個英文字母 a (例如 12345a)， 請將其視為字串處理，讀取時請記得忽略最後一個字元，輸出時請用字串結合的方式在最後面結合一個英文字母a(詳見範例)。",
      "inputDescription": "第一行：一個數字字串(含後置a)，代表第一塊石板上的數值 A。\n\n第二行：一個數字字串(含後置a)，代表第二塊石板上的數值 B。\n\n(註：字串長度介於 1 到 100 之間) 。",
      "outputDescription": "第一行：輸出計算結果字串(含後置a)，代表兩塊石板分別旋轉至最大值後相加的結果\n\n範例一\n\n輸入\n\n192a\n81a\n\n輸出\n\n273a\n\n範例說明\n\n輸入忽略後置a，192+81=273\n\n輸出273a\n\n範例二\n\n輸入\n\n999999999999000000000001a\n999999999999a\n\n輸出\n\n1000000000000000000000000a\n\n範例說明\n\n999999999999000000000001 和999999999999\n\n相加為1000000000000000000000000\n\n輸出時要加上含後置a如下：\n\n1000000000000000000000000a",
      "statement": {
        "description": "題目：古文明的能量融合\n\n題目說明\n\n考古學家在遺跡中發現了兩塊圓形的能量石板，上面刻著古老的數字代碼。根據解讀，這兩塊石板具有「相位旋轉」的特性。若想啟動遺跡的核心能源必須將這兩股最強的能量數值進行「大數加法」融合，所得的總和就是啟動核心的密碼。 請你編寫程式，根據考古學家輸入的兩塊石板數字，計算出融合後的最終能量數值 。\n\nNote: Scratch與 Blockly 積木運算大於16位的數字時已無法精確運算，因此輸入及輸出的數字字串最後方會強制加上一個英文字母 a (例如 12345a)， 請將其視為字串處理，讀取時請記得忽略最後一個字元，輸出時請用字串結合的方式在最後面結合一個英文字母a(詳見範例)。",
        "input": "第一行：一個數字字串(含後置a)，代表第一塊石板上的數值 A。\n\n第二行：一個數字字串(含後置a)，代表第二塊石板上的數值 B。\n\n(註：字串長度介於 1 到 100 之間) 。",
        "output": "第一行：輸出計算結果字串(含後置a)，代表兩塊石板分別旋轉至最大值後相加的結果\n\n範例一\n\n輸入\n\n192a\n81a\n\n輸出\n\n273a\n\n範例說明\n\n輸入忽略後置a，192+81=273\n\n輸出273a\n\n範例二\n\n輸入\n\n999999999999000000000001a\n999999999999a\n\n輸出\n\n1000000000000000000000000a\n\n範例說明\n\n999999999999000000000001 和999999999999\n\n相加為1000000000000000000000000\n\n輸出時要加上含後置a如下：\n\n1000000000000000000000000a"
      },
      "examples": [
        {
          "input": "192a\n81a",
          "output": "273a",
          "explanation": "輸入忽略後置a，192+81=273\n輸出273a"
        },
        {
          "input": "999999999999000000000001a\n999999999999a",
          "output": "1000000000000000000000000a",
          "explanation": "999999999999000000000001 和999999999999\n相加為1000000000000000000000000\n輸出時要加上含後置a如下：\n1000000000000000000000000a"
        }
      ],
      "testCases": [
        {
          "input": "11a\n22a",
          "expectedOutput": "33a",
          "output": "33a",
          "score": 10,
          "hidden": false
        },
        {
          "input": "14a\n61a",
          "expectedOutput": "75a",
          "output": "75a",
          "score": 15,
          "hidden": false
        },
        {
          "input": "333333333333111111111111a\n444444444444222222222222a",
          "expectedOutput": "777777777777333333333333a",
          "output": "777777777777333333333333a",
          "score": 20,
          "hidden": false
        },
        {
          "input": "111987654321111987654321a\n999a",
          "expectedOutput": "111987654321111987655320a",
          "output": "111987654321111987655320a",
          "score": 25,
          "hidden": false
        },
        {
          "input": "777777888888999999999999a\n222222222222999999999999a",
          "expectedOutput": "1000000111111999999999998a",
          "output": "1000000111111999999999998a",
          "score": 30,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "低",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    }
  ]
};

export default course;
